"""
ICU Specialist AI models for vital signs monitoring and clinical alerts.
"""
from datetime import datetime
from app import db


class VitalSign(db.Model):
    """
    Model for storing patient vital signs data.
    
    Captures continuous vital sign telemetry for ICU monitoring and
    clinical decision support. Foreign key links to Patient model.
    
    Attributes:
        id (int): Unique record identifier
        patient_id (int): Foreign key to Patient model
        heart_rate (int): Heart rate in beats per minute (BPM)
        blood_pressure_systolic (int): Systolic blood pressure (mmHg)
        blood_pressure_diastolic (int): Diastolic blood pressure (mmHg)
        oxygen_saturation (float): SpO2 percentage (0-100)
        temperature (float): Temperature in Celsius
        respiratory_rate (int): Respiratory rate per minute
        recorded_at (datetime): Timestamp when vitals were recorded
        created_at (datetime): Record creation timestamp
    """
    
    __tablename__ = 'vital_signs'
    
    id = db.Column(db.Integer, primary_key=True)
    patient_id = db.Column(db.Integer, db.ForeignKey('patients.id'), nullable=False, index=True)
    
    # Vital Signs Data
    heart_rate = db.Column(db.Integer, nullable=False)
    blood_pressure_systolic = db.Column(db.Integer, nullable=False)
    blood_pressure_diastolic = db.Column(db.Integer, nullable=False)
    oxygen_saturation = db.Column(db.Float, nullable=False)  # SpO2 percentage
    temperature = db.Column(db.Float, nullable=False)  # Celsius
    respiratory_rate = db.Column(db.Integer, nullable=False)
    
    # Timestamps
    recorded_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)
    
    # Relationship back to Patient
    patient = db.relationship('Patient', backref=db.backref('vital_signs', lazy=True, cascade='all, delete-orphan'))
    
    def __repr__(self):
        return f"<VitalSign(patient_id={self.patient_id}, hr={self.heart_rate}, spo2={self.oxygen_saturation})>"
    
    def to_dict(self):
        """
        Convert vital sign record to dictionary for API responses.
        
        Returns:
            dict: Dictionary representation of vital signs
        """
        return {
            'id': self.id,
            'patient_id': self.patient_id,
            'heart_rate': self.heart_rate,
            'blood_pressure_systolic': self.blood_pressure_systolic,
            'blood_pressure_diastolic': self.blood_pressure_diastolic,
            'oxygen_saturation': self.oxygen_saturation,
            'temperature': self.temperature,
            'respiratory_rate': self.respiratory_rate,
            'recorded_at': self.recorded_at.isoformat(),
            'created_at': self.created_at.isoformat()
        }


class ClinicalAlert(db.Model):
    """
    Model for storing clinical alerts generated by the ICU Specialist AI.
    
    Tracks alerts triggered by abnormal vital signs, including severity level,
    recommended interventions, and acknowledgment status.
    
    Attributes:
        id (int): Unique alert identifier
        patient_id (int): Foreign key to Patient model
        alert_level (str): Alert severity level ('Warning' or 'Critical')
        message (str): Human-readable alert message
        recommended_intervention (str): Recommended clinical action
        vital_sign_id (int): Foreign key to VitalSign that triggered alert
        is_acknowledged (bool): Whether alert has been acknowledged by clinician
        acknowledged_at (datetime): When alert was acknowledged
        acknowledged_by (str): User who acknowledged the alert
        created_at (datetime): Alert creation timestamp
    """
    
    __tablename__ = 'clinical_alerts'
    
    id = db.Column(db.Integer, primary_key=True)
    patient_id = db.Column(db.Integer, db.ForeignKey('patients.id'), nullable=False, index=True)
    alert_level = db.Column(db.String(20), nullable=False, index=True)  # 'Warning' or 'Critical'
    message = db.Column(db.Text, nullable=False)
    recommended_intervention = db.Column(db.Text, nullable=False)
    vital_sign_id = db.Column(db.Integer, db.ForeignKey('vital_signs.id'), nullable=True)
    
    # Acknowledgment tracking
    is_acknowledged = db.Column(db.Boolean, nullable=False, default=False, index=True)
    acknowledged_at = db.Column(db.DateTime, nullable=True)
    acknowledged_by = db.Column(db.String(100), nullable=True)
    
    # Timestamps
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)
    
    # Relationships
    patient = db.relationship('Patient', backref=db.backref('clinical_alerts', lazy=True, cascade='all, delete-orphan'))
    vital_sign = db.relationship('VitalSign', backref=db.backref('alerts', lazy=True))
    
    def __repr__(self):
        return f"<ClinicalAlert(patient_id={self.patient_id}, level={self.alert_level}, acknowledged={self.is_acknowledged})>"
    
    def to_dict(self):
        """
        Convert clinical alert to dictionary for API responses.
        
        Returns:
            dict: Dictionary representation of alert
        """
        return {
            'id': self.id,
            'patient_id': self.patient_id,
            'alert_level': self.alert_level,
            'message': self.message,
            'recommended_intervention': self.recommended_intervention,
            'vital_sign_id': self.vital_sign_id,
            'is_acknowledged': self.is_acknowledged,
            'acknowledged_at': self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            'acknowledged_by': self.acknowledged_by,
            'created_at': self.created_at.isoformat()
        }
    
    def acknowledge(self, acknowledged_by='System'):
        """
        Mark alert as acknowledged by clinician.
        
        Args:
            acknowledged_by (str): Username or identifier of acknowledging clinician
        """
        self.is_acknowledged = True
        self.acknowledged_at = datetime.utcnow()
        self.acknowledged_by = acknowledged_by
